---
title: "MULTIVARIATE ANALYSIS -- H1B VISA DATA"
author: "Ashita Shetty"
output:
  html_document: default
  pdf_document: default
---

**1. Ask an important question you want answered (1 at least)**

A: 

* What are the different factors that contribute to H1B being accepted?

* Which factors can be clubbed, or which factors correlate to each other the most?


**2. Answer why this question(s) is/are important to you:**

A: 
The prevailing job market presents a significant hurdle for international students, especially concerning job opportunities and H1B sponsorships. Securing an H1B visa is crucial for students looking to remain in the country after completing the OPT-STEM extension. Given the current market dynamics, where many companies are refraining from sponsoring visas, a comprehensive analysis of this situation becomes imperative.


**3. Find and collect data (need one dependent variable and more than 3 dependent variables)**

A: Uploaded on Github, under 'data/'
*(Haven't uploaded the main H1_B-2014.csv file in github because the file size was too large)*


**4. Describe your data (create a data dictionary):**

A: **File: H1_B-2014**

* LCA_CASE_NUMBER: Unique case number for the Labor Condition Application (LCA) - Independent Variable

* STATUS: Status of the LCA case (e.g., CERTIFIED, REJECTED) - Dependent Variable

* LCA_CASE_SUBMIT: Submission date of the LCA case - Independent Variable

* DECISION_DATE: Decision date for the LCA case- Independent Variable

* APP_DIFF: Difference between DECISION_DATE and LCA_CASE_SUBMIT - Independent Variable

* VISA_CLASS: Visa classification (e.g., H-1B)- Independent Variable

* LCA_CASE_EMPLOYMENT_START_DATE: Start date of employment as per the LCA - Independent Variable

* LCA_CASE_EMPLOYMENT_END_DATE: End date of employment as per the LCA - Independent Variable

* EMP_DIFF: Difference between LCA_CASE_EMPLOYMENT_END_DATE and LCA_CASE_EMPLOYMENT_START_DATE- Independent Variable 

* LCA_CASE_EMPLOYER_NAME: Name of the employer filing the LCA - Independent Variable

* LCA_CASE_EMPLOYER_ADDRESS: Address of the employer- Independent Variable

* LCA_CASE_EMPLOYER_CITY: City of the employer - Independent Variable

* LCA_CASE_EMPLOYER_STATE: State of the employer- Independent Variable

* LCA_CASE_EMPLOYER_POSTAL_CODE: Postal code of the employer- Independent Variable

* LCA_CASE_SOC_CODE: Standard Occupational Classification (SOC) code- Independent Variable

* LCA_CASE_SOC_NAME: SOC name corresponding to the code- Independent Variable

* LCA_CASE_JOB_TITLE: Job title for the LCA- Independent Variable

* LCA_CASE_WAGE_RATE_FROM: Minimum wage rate for the job- Independent Variable

* LCA_CASE_WAGE_RATE_TO: Maximum wage rate for the job- Independent Variable

* LCA_CASE_WAGE_RATE_UNIT: Unit of the wage rate (e.g., Year)- Independent Variable

* FULL_TIME_POS: Indicator of whether the position is full-time (Y/N)- Independent Variable

* TOTAL_WORKERS: Total number of workers for the case- Independent Variable

* LCA_CASE_WORKLOC1_CITY: City of the work location- Independent Variable

* LCA_CASE_WORKLOC1_STATE: State of the work location- Independent Variable

* PW_1: Prevailing wage for the job- Independent Variable

* PW_UNIT_1: Unit of the prevailing wage- Independent Variable

* PW_SOURCE_1: Source of the prevailing wage- Independent Variable

* OTHER_WAGE_SOURCE_1: Other wage source information- Independent Variable

* YR_SOURCE_PUB_1: Year of the prevailing wage source publication- Independent Variable

* LCA_CASE_NAICS_CODE: North American Industry Classification System (NAICS) code- Independent Variable

**File: NAICS_data**

* NAICS_CODE: North American Industry Classification System (NAICS) code- Independent Variable

* NAICS_TITLE: Title corresponding to the NAICS code- Independent Variable

**File: occupations**

* SOC Code: Standard Occupational Classification (SOC) code- Independent Variable

* Occupation Name: Name corresponding to the SOC code- Independent Variable


```{r}

```

